### PR TITLE
examples: sign-leaf-with-ca uses ca key for signing end entity cert

### PR DESCRIPTION
**Pull request by markdingram**

### CODE REVIEW

**Review by djc — APPROVED** [review]
Thanks, sorry for getting that wrong!

**Review by cpu — APPROVED** [review]
Oops, good catch. Thank you.

**Comment by cpu** [comment]
This is trivial enough I feel comfortable merging w/o waiting for another review.

**Comment by cpu** [comment]
> github-merge-queue bot removed this pull request from the merge queue due to failed status checks

Hmm, a bunch of jobs failed to even start. Nothing on [githubstatus](https://www.githubstatus.com/). Trying again

**Pull request merged**
