### PR TITLE
Upgrade x509-parser to 0.16

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Review by Rigidity — APPROVED** [review]

**Review by cpu — APPROVED** [review]
LGTM, thanks!

There are a couple of TODO's in unit tests we could knock out now, but I think it would be reasonable to do that in a separate PR. I can take a look later:

https://github.com/rustls/rcgen/blob/3c3e984e11efa4985ca596fe8ba917e6b676fe77/rcgen/tests/generic.rs#L174-L176


https://github.com/rustls/rcgen/blob/3c3e984e11efa4985ca596fe8ba917e6b676fe77/rcgen/tests/generic.rs#L196

**Comment by cpu** [comment]
@djc I have commits fixing up those two test TODOs. Are you OK with me pushing those into this branch or would you prefer I do it separately after this merges?

**Comment by djc** [comment]
Sure, you have the baton!

**Comment by cpu** [comment]
> Sure, you have the baton!

Pushed my changes :rocket:

**Comment by djc** [comment]
✅ Test changes LGTM.

**Review by est31 — APPROVED** [review]
great work

**Pull request merged**
