### PR TITLE
project: apply cargo fmt universally, verify in CI.

### PR DESCRIPTION
**Pull request by cpu**
Self-explanatory. Applies `cargo fmt` universally, adds a CI job to ensure consistent formatting going forward. No functional changes.

### CODE REVIEW

**Review by djc — APPROVED** [review]
To be explicit, here's why I think this is a good idea:

1. The default `cargo fmt` settings represent idiomatic style, that is used across most Rust projects
2. Automatic formatting tooling makes life easier for contributors
3. Style enforcement in CI avoids (some) additional review roundtrips due to stylistic concerns

**Comment by cpu** [comment]
> To be explicit, here's why I think this is a good idea

Thanks for adding motivating context. I should have done that in my PR description :+1: Your points echo the feelings I expressed [in this comment](https://github.com/rustls/rcgen/issues/85#issuecomment-1596156604).

**Comment by est31** [comment]
Btw, would it be possible to remove these coverage comments? they are put on every PR, even ones that don't touch anything related to tests. I think it's cool to have coverage reports you can browse online and look at graphs, but I don't think one needs to have a comment for each PR on how it changes the doc coverage.

As for autoformatters, I think there are some options that make cargo fmt nicer, I will make some experiments and will then propose something.

**Comment by cpu** [comment]
> Btw, would it be possible to remove these coverage comments?

I'll look into that.

> As for autoformatters, I think there are some options that make cargo fmt nicer, I will make some experiments and will then propose something.

@est31 Does this PR need to wait for that adjustment? The benefit of machine formatting is that if you change the rules of the formatter, you can run it again.

**Comment by djc** [comment]
> > As for autoformatters, I think there are some options that make cargo fmt nicer, I will make some experiments and will then propose something.
> 
> @est31 Does this PR need to wait for that adjustment? The benefit of machine formatting is that if you change the rules of the formatter, you can run it again.

@est31 friendly ping on this? Would be nice for further changes to get the formatting done first.

**Review by est31 — APPROVED** [review]

**Comment by est31** [comment]
It's a pity that `overflow_delimited_expr` isn't stable. Idk about you but I like former way more:

```
-		assert_eq!(uris, &[
-			"http://example.com/crl.der",
-			"http://crls.example.com/1234",
-			"ldap://example.com/crl.der"
-		]);
+		assert_eq!(
+			uris,
+			&[
+				"http://example.com/crl.der",
+				"http://crls.example.com/1234",
+				"ldap://example.com/crl.der"
+			]
+		);
```

**Comment by iamjpotts** [comment]
> It's a pity that `overflow_delimited_expr` isn't stable. Idk about you but I like former way more:
> 
> ```
> -		assert_eq!(uris, &[
> -			"http://example.com/crl.der",
> -			"http://crls.example.com/1234",
> -			"ldap://example.com/crl.der"
> -		]);
> +		assert_eq!(
> +			uris,
> +			&[
> +				"http://example.com/crl.der",
> +				"http://crls.example.com/1234",
> +				"ldap://example.com/crl.der"
> +			]
> +		);
> ```

I like the latter way, but I'm also glad that `rustfmt` isn't `black`

**Pull request merged**
