### PR TITLE
Streamline CI jobs

### PR DESCRIPTION
**Pull request by djc**
I've felt that CI in this project is relatively slow. Try to make it a bit faster.

### CODE REVIEW

**Comment by djc** [comment]
Hmm, it seems like the Windows and macOS builds are the long pole here. It looks like we have some caching in place for the Windows build at least, but it doesn't seem to be particularly effective?

**Comment by cpu** [comment]
>  It looks like we have some caching in place for the Windows build at least, but it doesn't seem to be particularly effective?

Indeed, I tried to cache the `vcpkg` stuff that seemed to be the main source of slowness (IIRC it's mainly fetching botan build deps?), but I'm not confident it actually worked the way I intended.

I wonder if it would be workable to limit the botan and openssl testing that require more native dependencies to fewer OS targets and assume the upstream projects are covering the platform specific aspects?

**Review by cpu — APPROVED** [review]
These seem like uncontroversial improvements to me :+1:

**Comment by djc** [comment]
> I wonder if it would be workable to limit the botan and openssl testing that require more native dependencies to fewer OS targets and assume the upstream projects are covering the platform specific aspects?

Seems pretty reasonable to me -- after all, I don't think we have any platform-specific code in this project?

**Review by est31 — APPROVED** [review]
good changes

**Comment by cpu** [comment]
@djc I think you might need to administratively merge this, or adjust the branch protection rules. The auto-merge is waiting on removed CI tasks to complete.

**Comment by djc** [comment]
Adjusted the branch protection rules to remove the rules that this PR got rid of.

**Pull request merged**
