### PR TITLE
Add ability to get a PublicKey from a KeyPair.

### PR DESCRIPTION
**Pull request by uglyoldbob**
This patch adds the ability to get a PublicKey struct directly from a KeyPair. I used this method to generate a csr and sign it with another certificate.

### CODE REVIEW

**Comment by djc** [comment]
This looks sensible to me, provided you can fix up the failing CI jobs?

**Review by est31 — APPROVED** [review]

**Comment by cpu** [comment]
>  I used this method to generate a csr and sign it with another certificate.

@uglyoldbob Can you expand on what you were trying to do here? 

I think the existing API would support the use-case you describe as follows:

1. Constructing a `KeyPair` somehow
2. Constructing `CertificateParams`.
3. Serializing a `CertificateSigningRequest` for the `KeyPair` with `CertificateParams::serialize_request(key_pair)`

I think you only need a way to construct a `PublicKey` from a `KeyPair` if you wanted to instantiate ` CertificateSigningRequest` yourself instead of using `serialize_request` and I'm not sure that's something we should aim to support. The `PublicKey` type is pretty useless outside of the crate since the `alg` and `raw` fields, and the `PublicKeyData` trait, are both crate internal.

**Comment by uglyoldbob** [comment]
Here is what I am doing that uses the public key method. [code here](https://github.com/uglyoldbob/iot/blob/master/src/ca.rs#L388)
I don't see CertificateParams::serialize_request in the latest release (0.12.1).

**Comment by cpu** [comment]
> I don't see CertificateParams::serialize_request in the latest release (0.12.1).

Indeed - we have a number of API changes queued in `main` that aren't in a release yet.

With 0.12.1's api you would:

* Construct a `KeyPair`, `key_pair`
* Construct `CertificateParams`, `params`.
* Set the `params.key_pair` to `Some(key_pair)`
* Construct a self-signed certificate with `Certificate::from_params(params)`, `cert`
* Serialize a CSR from the `Certificate` with [`cert.serialize_request_der`](https://docs.rs/rcgen/latest/rcgen/struct.Certificate.html#method.serialize_request_der), `csr_der`
* Create a `CertificateSigningRequest` with `CertificateSigningRequest::from_der(csr_der)`, `csr`
* Issue a cert from the CSR with `csr.serialize_der_with_signer(some_issuer_cert)`

It's certainly more steps in the 0.21.1 API, but still appears possible without modification to rcgen. 

I think with the API in `main` this change isn't required. Do you agree?

**Comment by cpu** [comment]
I'm going to go ahead and close this out. I think if we hadn't done the API rework this could have been a nice way to avoid a cumbersome step where you need to issue a self-signed certificate but the new API provides an ergonomic way to make a CSR from just params and a key pair.

Thanks again for the contribution!

**Pull request closed without merging**
