### PR TITLE
rcgen: 0.13.1 -> 0.13.2

### PR DESCRIPTION
**Pull request by lvkv**
Coming from https://github.com/rustls/rcgen/issues/285#issuecomment-2552866476. @djc did you want me to write the changelog as well? Don't want to step on your toes.

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Review by cpu — APPROVED** [review]
thanks!

**Comment by est31** [comment]
A changelog would be nice, otherwise LGTM

**Comment by djc** [comment]
I'll generate a changelog when I publish.

**Comment by djc** [comment]
@est31 so all the other rustls projects use GitHub releases and their generated changelogs instead of a manually curated `CHANGELOG.md`. I forget how much we have discussed this before, but would you be open to using that? We would pull out manually written high-level release notes for anything of particular interest to users. I would be willing to convert the old `CHANGELOG.md` contents into GitHub releases if that helps.

**Comment by est31** [comment]
Personally I'm not a fan of github releases. they are useful for attaching downloadable build artifacts and advertise the release on github, but they are github proprietary, are paginated on a very small scale, and you need network access to access them. `CHANGELOG.md` on the other hand sits in any clone of the repository and gets shipped to users via cargo vendor.

Doing both has some advantages, but if it is you who are writing the changelogs then I don't want to tell you what to do. Maybe we keep `CHANGELOG.md` and say that any newer release can be found on github releases?

**Comment by djc** [comment]
> Doing both has some advantages, but if it is you who are writing the changelogs then I don't want to tell you what to do. Maybe we keep CHANGELOG.md and say that any newer release can be found on github releases?

Will do, thanks!

**Comment by djc** [comment]
* Published rcgen v0.13.2 at registry `crates-io`
* [new tag]         v0.13.2 -> v0.13.2
* [Release notes](https://github.com/rustls/rcgen/releases/tag/v0.13.2)

**Pull request merged**
